# Generated by Django 5.2.7 on 2025-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summarizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du résumé', max_length=200)),
                ('user_input', models.TextField(help_text='Entrée utilisateur (problème émotionnel ou à résoudre)')),
                ('summary', models.TextField(blank=True, help_text='Résumé généré (sera rempli par IA plus tard)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
