# Generated by Django 5.2.7 on 2025-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Heureux'), ('neutral', 'Neutre'), ('sad', 'Triste'), ('angry', 'En colère'), ('excited', 'Excité'), ('tired', 'Fatigué')], max_length=20),
        ),
    ]
