# Generated by Django 5.2.7 on 2025-10-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='accomplishments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='achievement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='daily_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Échelle 1-5', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='favorite_moment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='gratitude',
            field=models.TextField(blank=True, help_text='Liste (ex: 3 éléments, un par ligne)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='lesson_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='location',
            field=models.CharField(blank=True, choices=[('home', 'Maison'), ('work', 'Travail'), ('outside', 'Extérieur'), ('travel', 'Voyage'), ('cafe', 'Café'), ('nature', 'Nature')], max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='main_mood_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Échelle 1-5', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='main_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='meals_quality',
            field=models.CharField(blank=True, choices=[('excellent', '🍎 Excellente'), ('average', '🥪 Moyenne'), ('poor', '🍟 Faible')], max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='meditation',
            field=models.CharField(blank=True, choices=[('no', 'Non'), ('5m', '5min'), ('10m', '10min'), ('15m+', '15min+')], max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('15m', '15min'), ('30m', '30min'), ('1h', '1h'), ('1h+', '1h+')], max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='physical_health',
            field=models.CharField(blank=True, choices=[('good', '👍 Bon'), ('ok', '➡️ Moyen'), ('bad', '👎 Mauvais')], max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='screen_time',
            field=models.CharField(blank=True, choices=[('1-2h', '1-2h'), ('3-4h', '3-4h'), ('5h+', '5h+')], max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', '🌸 Printemps'), ('summer', '☀️ Été'), ('autumn', '🍂 Automne'), ('winter', '❄️ Hiver')], max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='secondary_themes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sleep_quality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Échelle 1-5', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='surprise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Matin'), ('noon', 'Midi'), ('afternoon', 'Après-midi'), ('evening', 'Soir'), ('night', 'Nuit')], max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', '☀️ Ensoleillé'), ('cloudy', '⛅ Nuageux'), ('rain', '🌧️ Pluie'), ('storm', '⛈️ Orage'), ('snow', '❄️ Neige')], max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='detailed_emotions',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.emotion'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='people_present',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.personcategory'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.tag'),
        ),
    ]
