# Generated by Django 5.2.7 on 2025-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_emotion_personcategory_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, upload_to='journal_media/'),
        ),
    ]
