# Generated by Django 4.2 on 2025-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positif'), ('neutral', 'Neutre'), ('negative', 'Négatif')], default='neutral', max_length=12),
        ),
    ]
