# Generated by Django 5.2.7 on 2025-10-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField(help_text='Décris ici ton problème, ton ressenti ou ta situation.', verbose_name='Texte du problème')),
                ('summary', models.TextField(blank=True, null=True, verbose_name="Résumé généré par l'IA")),
                ('emotion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Émotion dominante')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie du problème')),
                ('ai_solution', models.TextField(blank=True, null=True, verbose_name='Solution ou conseil IA')),
                ('feedback', models.CharField(blank=True, choices=[('helpful', 'Utile'), ('neutral', 'Neutre'), ('not_helpful', 'Pas utile')], max_length=50, null=True, verbose_name="Avis de l'utilisateur sur la réponse IA")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='user.user')),
            ],
            options={
                'verbose_name': 'Entrée de problème',
                'verbose_name_plural': 'Entrées de problèmes',
                'ordering': ['-created_at'],
            },
        ),
    ]
