# Generated by Django 5.2.7 on 2025-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalnote',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('idea', 'Idea'), ('problem', 'Problem'), ('project', 'Project'), ('meeting', 'Meeting'), ('reminder', 'Reminder'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='vocalnote',
            name='context',
            field=models.TextField(blank=True, help_text='Context description', null=True),
        ),
        migrations.AddField(
            model_name='vocalnote',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords'),
        ),
        migrations.AddField(
            model_name='vocalnote',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='List of detected topics'),
        ),
    ]
